services:

  database:
    container_name: database
    image: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=cloudstorage
  back-server:
    build: .
    links:
      - database
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/cloudstorage
    depends_on:
      - database
  #client:
  #  container_name: frontend-client
  #  build:
  #    context: front
  #    dockerfile: Dockerfile
  #  image: cloudstoragefront
  #  ports:
  #    - "8080:8080"